version: '3.9'

services:

  postgres:
    image: postgres:16-alpine
    container_name: gestor_errores_db
    environment:
      POSTGRES_DB: gestor_errores
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: gestor_errores_app
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DB: gestor_errores
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      SPRING_PROFILES_ACTIVE: docker

    depends_on:
      - postgres

volumes:
  postgres_data: